version: '3.6'

services:
  dbcfs:
    build:
      context: .
      args:
        JAR_FILE: build/libs/*.jar
    ports:
      - "8080:8080"
      - "34197:34197/udp"
    volumes:
      - ./data:/mnt
