server:
  port: 8080
pebble:
  prefix: templates/
  suffix: .peb
dbcfs:
  discord:
    token: DISCORD_BOT_TOKEN_HERE
    owner: YOUR_DISCORD_USERNAME_HERE
    commandPrefix: .
    intervalInSeconds: 3  # FIXME Not used yet (Should replace const val in Notifier companion object)
  db:
    path: /mnt/index.sqlite
  factorio:
    username: YOUR_FACTORIO_USERNAME_HERE
    token: YOUR_FACTORIO_AUTH_TOKEN_HERE (see https://wiki.factorio.com/Web_authentication_API)
    cookie: YOUR_FACTORIO_WEBSITE_SESSION_COOKIE_HERE
  server:
    domain: http://my_domain_for_url_bases
